import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const body = await req.json();

    const messages = body?.messages;

    if (!messages || !Array.isArray(messages)) {
      return NextResponse.json(
        { reply: "Missing or invalid messages array." },
        { status: 400 }
      );
    }

    // 🔹 This is where your AI will go later
    // For now we simulate a response

    const userMessage = messages[messages.length - 1]?.content || "";

    const simulatedResponse = `
Finley Analysis:

Loan Direction:
Based on the provided income and debt, this borrower appears to qualify for conventional financing, subject to full underwriting review.

Risk Flags:
- High LTV (above 90%)
- Limited down payment relative to purchase price

Next Steps:
- Review AUS findings (DU/LP)
- Confirm income documentation
- Evaluate PMI impact and rate structure
- Consider lender overlays for high LTV scenarios

(Generated by Beyond Intelligence™)
    `.trim();

    return NextResponse.json({
      reply: simulatedResponse,
    });
  } catch (error) {
    return NextResponse.json(
      { reply: "Server error processing request." },
      { status: 500 }
    );
  }
}
